Repository ArtNeplatform/front, pull requests merged in 2025-02, with the labels that each got.

#10 Feature/#3 - Prettier 추가, 정방형 및 너비 우선 GridContainer 추가 구현
  .prettierrc
  README.md
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/Example/artist.ts
  src/apis/axios.ts
  src/apis/error.ts
  src/apis/type.ts
  src/components/common/ArtWork/index.style.ts
  src/components/common/ArtWork/index.tsx
  src/components/common/AuthCheckRoute/index.tsx
  src/components/common/AuthorProfile/index.style.ts
  src/components/common/AuthorProfile/index.tsx
  src/components/common/CustomImageContainer/index.style.ts
  src/components/common/CustomImageContainer/index.tsx
  src/components/common/Error/DefaultErrorFallbackUI/index.style.ts
  src/components/common/Error/DefaultErrorFallbackUI/index.tsx
  src/components/common/ErrorBoundary/index.tsx
  src/components/common/FallbackUI/index.tsx
  src/components/common/Header/index.style.ts
  src/components/common/Header/index.tsx
  src/components/common/HoveringModal/index.style.ts
  src/components/common/HoveringModal/index.tsx
  src/components/common/PageLayout/index.style.ts
  src/components/common/PageLayout/index.tsx
  src/components/common/ScrollToTop/index.ts
  src/components/common/SortingChooseModal/index.style.ts
  src/components/common/SortingChooseModal/index.tsx
  src/components/common/SortingTextButton/index.style.ts
  src/components/common/SortingTextButton/index.tsx
  src/components/common/SquareGridContainer/index.style.ts
  src/components/common/SquareGridContainer/index.tsx
  src/components/common/ThemeChooser/index.style.ts
  src/components/common/ThemeChooser/index.tsx
  src/components/common/WidthFirstGridContainer/index.style.ts
  src/components/common/WidthFirstGridContainer/index.tsx
  src/constants/queryKeys.ts
  src/contexts/authContext.tsx
  src/hooks/apis/useGetArtistList.ts
  src/main.tsx
  src/pages/home.tsx
  src/pages/notFound.tsx
  src/pages/test.tsx
  src/router.tsx
  src/styles/global.tsx
  src/styles/text.tsx
  src/styles/theme.ts
  src/test/TestComponent/index.style.ts
  src/test/TestComponent/index.tsx
  src/types/artist.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: ✨ feature, 🎨 refactor, 👨🏻 규진 👨🏻

#11 Feature/#5 - CircleCheckBox, RectangleCheckBox, Common Button, FIlterModal 구현
  src/assets/svg/icon-check.svg
  src/components/common/CircleCheckBox/index.style.ts
  src/components/common/CircleCheckBox/index.tsx
  src/components/common/CommonButton/index.style.ts
  src/components/common/CommonButton/index.tsx
  src/components/common/FilterModal/index.style.ts
  src/components/common/FilterModal/index.tsx
  src/components/common/RectangleCheckBox/index.style.ts
  src/components/common/RectangleCheckBox/index.tsx
  src/test/TestComponent/index.style.ts
  src/test/TestComponent/index.tsx
Labels: ✨ feature, 🍀 서윤 🍀

#9 Feature/#7 - 공통 컴포넌트 구현 (작가 상세 카테고리, 공통 input, 페이징 버튼, 마이페이지 사이드 바) ✨ feature New Feature
  package.json
  pnpm-lock.yaml
  src/components/common/AuthorDetailCategory/index.style.ts
  src/components/common/AuthorDetailCategory/index.tsx
  src/components/common/CommonInput/index.style.ts
  src/components/common/CommonInput/index.tsx
  src/components/common/MyPageSideBar/index.style.ts
  src/components/common/MyPageSideBar/index.tsx
  src/components/common/PagingButtons/index.style.ts
  src/components/common/PagingButtons/index.tsx
  src/test/TestComponent/index.tsx
Labels: ✨ feature, ☁ 하늘 ☁

#15 Feature/#12 - 공통 컴포넌트 리팩토링 & 로그인, 작품 등록, 경매 등록 페이지 퍼블리싱
  .gitignore
  index.html
  package.json
  pnpm-lock.yaml
  src/assets/svg/check-icon.svg
  src/assets/svg/google.svg
  src/assets/svg/kakao_talk.svg
  src/assets/svg/picture-register.svg
  src/components/common/ArtWork/index.style.ts
  src/components/common/ArtWork/index.tsx
  src/components/common/CircleCheckBox/index.tsx
  src/components/common/CommonButton/index.style.ts
  src/components/common/CommonButton/index.tsx
  src/components/common/Divider/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/PageLayout/index.tsx
  src/components/common/RectangleCheckBox/index.tsx
  src/components/common/SquareGridContainer/index.tsx
  src/components/common/ThemeChooser/index.style.ts
  src/components/common/ThemeChooser/index.tsx
  src/main.tsx
  src/pages/artwork-register/components/ArtworkDetailBelowLabel/index.style.ts
  src/pages/artwork-register/components/ArtworkDetailBelowLabel/index.tsx
  src/pages/artwork-register/components/GenreCheckBox/index.style.ts
  src/pages/artwork-register/components/GenreCheckBox/index.tsx
  src/pages/artwork-register/components/ImageUploader/index.style.ts
  src/pages/artwork-register/components/ImageUploader/index.tsx
  src/pages/artwork-register/components/MaterialCheckBox/index.style.ts
  src/pages/artwork-register/components/MaterialCheckBox/index.tsx
  src/pages/artwork-register/constants/genres.ts
  src/pages/artwork-register/constants/themes.ts
  src/pages/artwork-register/hooks/useArtworkRegisterForm.ts
  src/pages/artwork-register/index.style.ts
  src/pages/artwork-register/index.tsx
  src/pages/auction-register/hooks/useAuctionRegisterForm.ts
  src/pages/auction-register/index.style.ts
  src/pages/auction-register/index.tsx
  src/pages/login/hooks/useGoogleLogin.ts
  src/pages/login/hooks/useKakaotalkLogin.ts
  src/pages/login/index.style.ts
  src/pages/login/index.tsx
  src/router.tsx
  src/styles/text.tsx
  src/test/TestComponent/index.tsx
Labels: ✨ feature, 🎨 refactor, 👨🏻 규진 👨🏻

#18 Feat: CI/CD 설정 및 배포
  .github/workflows/git-action-cicd.yaml
Labels: ✨ feature, 👨🏻 규진 👨🏻

#20 Feature/#17 - 전시 등록 및 경매 등록 페이지 구현 및 Custom Hook 정의
  .gitignore
  src/apis/Example/artist.ts
  src/apis/auctionRegister/getAvailableArtworks.ts
  src/apis/auctionRegister/type.ts
  src/apis/axios.ts
  src/apis/register/postAuthRegister.ts
  src/apis/register/type.ts
  src/apis/type.ts
  src/components/common/CommonButton/index.style.ts
  src/components/common/CommonButton/index.tsx
  src/components/common/FilterModal/index.tsx
  src/constants/queryKeys.ts
  src/pages/auction-register/hooks/useGetAvailableArtwork.ts
  src/pages/auction-register/index.tsx
  src/pages/exhibit-register/components/StepOne/index.style.ts
  src/pages/exhibit-register/components/StepOne/index.tsx
  src/pages/exhibit-register/components/StepThree/index.style.ts
  src/pages/exhibit-register/components/StepThree/index.tsx
  src/pages/exhibit-register/components/StepTwo/index.style.ts
  src/pages/exhibit-register/components/StepTwo/index.tsx
  src/pages/exhibit-register/hooks/useExhibitRegister.ts
  src/pages/exhibit-register/index.style.ts
  src/pages/exhibit-register/index.tsx
  src/pages/login/hooks/useGoogleLogin.ts
  src/pages/login/hooks/useKakaotalkLogin.ts
  src/pages/login/index.tsx
  src/pages/register/hooks/usePostAuthRegister.ts
  src/pages/register/hooks/useRegisterForm.ts
  src/pages/register/index.style.ts
  src/pages/register/index.tsx
  src/router.tsx
  src/test/TestComponent/index.tsx
Labels: ✨ feature, 👨🏻 규진 👨🏻

#21 Fix: CI/CD 설정 -3
  .github/workflows/git-action-cicd.yaml
Labels: ✨ feature, 👨🏻 규진 👨🏻

#22 Feature/#17 - 작품 등록 API 구현 및 공통 컴포넌트 확장성 추가
  src/apis/artworkRegister/postArtworkRegister.ts
  src/apis/artworkRegister/type.ts
  src/apis/auctionRegister/postAuctionRegister.ts
  src/apis/auctionRegister/type.ts
  src/apis/axios.ts
  src/components/common/ArtWork/index.style.ts
  src/components/common/ArtWork/index.tsx
  src/components/common/ThemeChooser/index.tsx
  src/constants/mutationKey.ts
  src/constants/queryKeys.ts
  src/main.tsx
  src/pages/artwork-register/components/GenreCheckBox/index.tsx
  src/pages/artwork-register/components/MaterialCheckBox/index.tsx
  src/pages/artwork-register/constants/genres.ts
  src/pages/artwork-register/hooks/useArtworkRegisterForm.ts
  src/pages/artwork-register/index.tsx
  src/pages/auction-register/components/AuctionModal/index.style.ts
  src/pages/auction-register/components/AuctionModal/index.tsx
  src/pages/auction-register/hooks/useAuctionRegisterForm.ts
  src/pages/auction-register/index.style.ts
  src/pages/auction-register/index.tsx
  src/pages/register/hooks/usePostAuthRegister.ts
Labels: ✨ feature, 👨🏻 규진 👨🏻

#30 Feature/#29 - 마이페이지 내 작품구매자 페이지 버튼 UI 구현
  src/apis/authorPage/type.ts
  src/apis/axios.ts
  src/apis/kakaoPay/paymentAuthorization.ts
  src/apis/kakaoPay/paymentPreparation.ts
  src/apis/kakaoPay/type.ts
  src/apis/myPage/type.ts
  src/contexts/authContext.tsx
  src/pages/artBuyerPage/ArtBuyerPage.tsx
  src/pages/artBuyerPage/components/menuMyPage/Auction/index.style.ts
  src/pages/artBuyerPage/components/menuMyPage/Auction/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/MyCollection/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/Payment/index.style.ts
  src/pages/artBuyerPage/components/menuMyPage/Payment/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/index.tsx
  src/pages/artBuyerPage/components/purchasedWorks/index.tsx
  src/pages/artBuyerPage/hooks/useGetPurchasedArtworks.ts
  src/pages/artBuyerPage/hooks/useKakaoPay.ts
  src/pages/auction-register/index.tsx
  src/pages/auction/index.tsx
  src/pages/author/index.tsx
  src/pages/authorPage/components/managementWorks/artWorks/index.tsx
  src/pages/authorPage/components/managementWorks/auctioningWorks/index.tsx
  src/pages/authorPage/components/managementWorks/exhibitions/index.tsx
  src/pages/authorPage/components/menuMyPage/artworkCollection/index.tsx
  src/pages/authorPage/hooks/useGetAuthorArtworksExhibitions.ts
  src/pages/authorPage/hooks/useGetAuthorProfile.ts
  src/pages/exhibition/index.tsx
  src/pages/main/hooks/useCarousel.ts
  src/pages/register/index.tsx
  src/router.tsx
  src/styles/text.tsx
  src/test/TestComponent/index.tsx
Labels: ✨ feature, 😽 찬영 😽

#35 Fix: build 오류 수정
  src/apis/authorPage/type.ts
  src/pages/artBuyerPage/ArtBuyerPage.tsx
  src/pages/artBuyerPage/components/menuMyPage/MyCollection/index.tsx
  src/pages/artBuyerPage/components/purchasedWorks/index.tsx
  src/pages/artBuyerPage/hooks/useGetPurchasedArtworks.ts
  src/pages/auction-register/index.tsx
  src/pages/authorPage/components/managementWorks/artWorks/index.tsx
  src/pages/authorPage/components/managementWorks/auctioningWorks/index.tsx
  src/pages/authorPage/components/managementWorks/exhibitions/index.tsx
  src/pages/authorPage/components/menuMyPage/artworkCollection/index.tsx
  src/pages/authorPage/hooks/useGetAuthorArtworksExhibitions.ts
  src/pages/authorPage/hooks/useGetAuthorProfile.ts
  src/styles/text.tsx
  src/test/TestComponent/index.tsx
Labels: 🐛 fix, ☁ 하늘 ☁

#40 Refactor/#39 - 컬러 팔레트 색 적용 수정
  src/components/common/CircleCheckBox/index.style.ts
  src/components/common/RectangleCheckBox/index.style.ts
  src/pages/artwork-detail/components/DetailInform/index.style.ts
  src/pages/artwork-detail/components/MoreButton/index.style.ts
  src/pages/artwork-detail/index.style.ts
  src/pages/artwork/components/SelectedFilter/index.style.ts
  src/pages/artwork/index.style.ts
  src/pages/main/index.style.ts
  src/styles/text.tsx
  src/styles/theme.ts
Labels: 🐛 fix, 🎨 refactor, 🍀 서윤 🍀

#38 Fix: 배포 환경 websocket 오류 수정
  src/pages/auction-detail/hooks/useWebSocket.ts
Labels: 🐛 fix, ☁ 하늘 ☁

#43 Refactor/#41 - 작품 상세 UI 수정
  src/assets/svg/icon-plus.svg
  src/pages/artwork-detail/index.style.ts
  src/pages/artwork-detail/index.tsx
Labels: 🎨 refactor, 🍀 서윤 🍀

#44 Refactor: 작가 상세 UI 수정
  src/components/common/ExhibitionItem/index.style.ts
  src/pages/author-detail/components/AuthorProfile/index.style.ts
  src/pages/author-detail/components/AuthorProfile/index.tsx
  src/pages/author-detail/index.tsx
Labels: 🎨 refactor, ☁ 하늘 ☁

#45 Fix: 배포 환경 websocket 오류 수정
  src/pages/auction-detail/hooks/useWebSocket.ts
Labels: 🐛 fix, ☁ 하늘 ☁

#48 Refactor/#34 - 소셜 로그인 구현 (카카오, 구글) 및 전시하기
  package.json
  pnpm-lock.yaml
  src/apis/exhibit-register/getExhibitAvailableArtwork.ts
  src/apis/exhibit-register/getExhibitBackgroundImages.ts
  src/apis/exhibit-register/types.ts
  src/apis/register/oAuthLogin.ts
  src/apis/register/postAuthRegister.ts
  src/apis/register/type.ts
  src/assets/png/exhibit-register/exhibition_image_1.png
  src/assets/png/exhibit-register/exhibition_image_2.png
  src/assets/png/exhibit-register/exhibition_image_3.png
  src/assets/png/exhibit-register/exhibition_image_4.png
  src/assets/png/exhibit-register/exhibition_image_5.png
  src/assets/png/exhibit-register/exhibition_image_6.png
  src/assets/png/exhibit-register/exhibition_image_7.png
  src/assets/png/exhibit-register/exhibition_image_8.png
  src/components/common/Header/index.style.ts
  src/components/common/Header/index.tsx
  src/components/common/PageLayout/index.tsx
  src/constants/queryKeys.ts
  src/pages/artwork-register/hooks/useArtworkRegisterForm.ts
  src/pages/auction/index.style.ts
  src/pages/auction/index.tsx
  src/pages/author/index.style.ts
  src/pages/author/index.tsx
  src/pages/exhibit-register/components/StepOne/index.style.ts
  src/pages/exhibit-register/components/StepOne/index.tsx
  src/pages/exhibit-register/components/StepThree/index.style.ts
  src/pages/exhibit-register/components/StepThree/index.tsx
  src/pages/exhibit-register/components/StepTwo/index.style.ts
  src/pages/exhibit-register/components/StepTwo/index.tsx
  src/pages/exhibit-register/hooks/useExhibitRegister.ts
  src/pages/exhibit-register/hooks/useGetExhibitAvailableArtwork.ts
  src/pages/exhibit-register/hooks/useGetExhibitBackground.ts
  src/pages/exhibit-register/index.tsx
  src/pages/exhibition/index.style.ts
  src/pages/exhibition/index.tsx
  src/pages/login-redirect/index.tsx
  src/pages/login/hooks/useGoogleLogin.ts
  src/pages/login/hooks/useKakaotalkLogin.ts
  src/pages/login/hooks/useOauthLogin.ts
  src/pages/login/index.tsx
  src/pages/register/hooks/usePostAuthRegister.ts
  src/pages/register/hooks/useRegisterForm.ts
  src/pages/register/index.tsx
  src/router.tsx
Labels: ✨ feature, 👨🏻 규진 👨🏻

#47 Feature/#28 - 작품 구매자/ 작가 마이페이지 조회 API 연결
  src/apis/auction/type.ts
  src/apis/kakaoPay/paymentAuthorization.ts
  src/apis/kakaoPay/paymentPreparation.ts
  src/apis/kakaoPay/type.ts
  src/apis/main/type.ts
  src/apis/myPage/myPage.ts
  src/apis/mypage-author/account.ts
  src/apis/mypage-author/author.ts
  src/apis/mypage-author/myPage/myPage.ts
  src/apis/mypage-author/myPage/type.ts
  src/apis/mypage-author/profile.ts
  src/apis/mypage-author/type.ts
  src/apis/mypage-buyer/artBuyer.ts
  src/apis/mypage-buyer/artWork.ts
  src/apis/mypage-buyer/myPage/myPage.ts
  src/apis/mypage-buyer/myPage/type.ts
  src/apis/mypage-buyer/type.ts
  src/assets/svg/Icon_heart.svg
  src/components/common/ArtWork/index.tsx
  src/components/common/AuthorProfile/index.tsx
  src/constants/queryKeys.ts
  src/pages/artBuyerPage/ArtBuyerPage.tsx
  src/pages/artBuyerPage/components/accountSettings/basicInfo/index.style.ts
  src/pages/artBuyerPage/components/accountSettings/basicInfo/index.tsx
  src/pages/artBuyerPage/components/menuChooser/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/Auction/index.style.ts
  src/pages/artBuyerPage/components/menuMyPage/Auction/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/MyCollection/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/Payment/index.style.ts
  src/pages/artBuyerPage/components/menuMyPage/Payment/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/profile/index.tsx
  src/pages/artBuyerPage/components/purchasedWorks/index.tsx
  src/pages/artBuyerPage/hooks/useGetBuyerMypage.ts
  src/pages/artBuyerPage/hooks/useGetPurchasedArtworks.ts
  src/pages/artBuyerPage/hooks/useKakaoPay.ts
  src/pages/artBuyerPage/hooks/useUpdateUserInfo.ts
  src/pages/artwork/index.tsx
  src/pages/authorPage/components/menuMyPage/Auction/index.tsx
  src/pages/authorPage/components/menuMyPage/artworkCollection/index.tsx
  src/pages/authorPage/components/menuMyPage/index.tsx
  src/pages/authorPage/components/menuMyPage/profile/index.style.ts
  src/pages/authorPage/components/menuMyPage/profile/index.tsx
  src/pages/authorPage/hooks/useGetAuthorArtworksExhibitions.ts
  src/pages/authorPage/hooks/useGetAuthorMypage.ts
  src/pages/authorPage/hooks/useGetAuthorProfile.ts
  src/pages/authorPage/hooks/useSaveAuthorBankInfo.ts
  src/pages/authorPage/hooks/useUpdateAuthorInfo.ts
  src/pages/authorPage/hooks/useUpdateAuthorProfile.ts
  src/router.tsx
  src/test/TestComponent/index.tsx
Labels: ✨ feature, 🎨 refactor, 😽 찬영 😽

#50 Refactor/#49 - 메인 경매 가격 추가 및 작품 상세 index 수정
  src/pages/artwork-detail/index.tsx
  src/pages/main/index.style.ts
  src/pages/main/index.tsx
Labels: 🐛 fix, 🎨 refactor, 🍀 서윤 🍀

#46 Feature/#36 - 경매 좋아요, 좋아요 취소 API 연결
  src/apis/auction/postAuctionLike.ts
  src/apis/auction/postAuctionUnlike.ts
  src/components/common/ArtWork/index.tsx
  src/constants/mutationKey.ts
  src/pages/auction/hooks/useAuctionLike.ts
  src/pages/auction/hooks/useAuctionUnlike.ts
  src/pages/auction/index.tsx
Labels: ✨ feature, ☁ 하늘 ☁

#51 Feature/#31 - 작품 내 공간 UI
  src/assets/png/example_space.png
  src/assets/png/example_space_2.png
  src/assets/png/example_space_3.png
  src/assets/png/example_space_4.png
  src/assets/png/example_space_5.png
  src/assets/svg/space-left.svg
  src/assets/svg/space-right.svg
  src/pages/artwork-detail/index.style.ts
  src/pages/artwork-detail/index.tsx
Labels: ✨ feature, 🍀 서윤 🍀

#53 Refactor/#34 - 전역 로딩, 에러, 미등록 페이지 (404 Error) 퍼블리싱
  src/components/common/Error/DefaultErrorFallbackUI/index.style.ts
  src/components/common/Error/DefaultErrorFallbackUI/index.tsx
  src/components/common/PrimarySpinner/index.style.ts
  src/components/common/PrimarySpinner/index.tsx
  src/pages/exhibit-register/components/StepThree/index.tsx
  src/pages/not-found/index.style.ts
  src/pages/not-found/index.tsx
  src/pages/notFound.tsx
  src/router.tsx
Labels: ✨ feature, 👨🏻 규진 👨🏻

#56 Fix: 경매 상세 조회 이미지 수정
  src/pages/auction-detail/hooks/usePostAuctionBid.ts
  src/pages/auction-detail/index.tsx
Labels: 🐛 fix, ☁ 하늘 ☁

#58 Refactor: 경매 완료 시 처리
  src/pages/auction-detail/index.tsx
Labels: 🎨 refactor, ☁ 하늘 ☁

#59 Refactor: 라우터 세부 수정
  src/components/common/Header/index.tsx
  src/components/common/PageLayout/index.tsx
Labels: 🎨 refactor, 😽 찬영 😽

#62 Refactor: 헤더 전시 탭 추가
  src/components/common/Header/index.tsx
Labels: 🎨 refactor, ☁ 하늘 ☁

#63 Feature/#31
  src/assets/svg/space-register.svg
  src/pages/artwork-detail/components/MySpaceModal/index.style.ts
  src/pages/artwork-detail/components/MySpaceModal/index.tsx
  src/pages/artwork-detail/index.tsx
  src/pages/artwork/index.style.ts
  src/pages/artwork/index.tsx
Labels: ✨ feature, 🐛 fix, 🍀 서윤 🍀

#67 Fix: 텍스트 수정
  src/contexts/authContext.tsx
  src/pages/artBuyerPage/components/menuMyPage/Auction/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/Payment/index.tsx
  src/pages/login-redirect/index.tsx
  src/pages/main/hooks/useCarousel.ts
Labels: 🐛 fix, 😽 찬영 😽

#69 Fix: 마이페이지 UI 세부 수정
  src/pages/artBuyerPage/components/menuMyPage/Auction/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/Payment/index.tsx
  src/pages/artBuyerPage/components/menuMyPage/index.tsx
  src/pages/artBuyerPage/components/purchasedWorks/index.tsx
  src/pages/authorPage/components/menuMyPage/Auction/index.tsx
Labels: 🐛 fix, 🎨 refactor, 😽 찬영 😽
